# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.

title: Projectyl
email: mukherjeeabhirup44@gmail.com
subtitle: "Physics internships in India"
description: "An internship with the correct scientist can be of immense help in starting your career in research!"
url: "https://projectyl.github.io/"
search: true
logo: "/assets/images/general/logo.svg"
minimal_mistakes_skin: "air" # "default", "air", "aqua", "contrast", "dark", "dirt", "neon", "mint", "plum", "sunrise"

github: [metadata]

# Build settings
markdown: kramdown
remote_theme: mmistakes/minimal-mistakes
permalink: /:categories/:title/
paginate: 5 # amount of posts to show
paginate_path: /_posts/page:num/

include:
  - _pages

# Plugins (previously gems:)
plugins:
  - jekyll-include-cache
defaults:
  - scope:
      path: ""
      type: posts
    values:
      layout: single
      author_profile: false
      read_time: false
      comments: true
      share: true
      related: false
      sidebar:
        nav: categories
      header:
        actions:
          - label: "Internships"
            url: /summer/
          - label: "Updates"
            url: /notifs/
          - label: "Contact Us"
            url: /contact/
  - scope:
      path: "_pages"
      type: pages
    values:
      layout: single
      author_profile: false
      comments: true
      share: true
      related: false
      sidebar:
        nav: categories


category_archive:
  type: liquid
  path: /categories/
tag_archive:
  type: liquid
  path: /tags/

comments:
#   provider               : "disqus", "discourse", "facebook", "staticman", "staticman_v2", "utterances", "custom"
  provider: "facebook"
  facebook:
    appid: "690522761992870" # optional
    num_posts: 100 # 5 (default)
    colorscheme: "light" # "light" (default), "dark"

analytics:
  provider: "google-gtag"
  google:
    tracking_id: "G-MYJJD2WVS1"
    anonymize_ip: false # default

# Social Sharing
instagram:
  username               : projectyl_india
instagram:
  username               : projectyl_india
instagram:
  username               : projectyl_india
instagram:
  username               : projectyl_india


social:
  type                   : Organization
  name                   : Projectyl
  links: # An array of links to social media profiles
    - "https://twitter.com/Projectyl125295"
    - "https://www.facebook.com/projectyl.in"
    - "https://instagram.com/projectyl_india/"
    - "https://www.linkedin.com/in/projectyl-india-52ab5a26a/"
